name = "test-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "test-email"
database_id = "e65f099d-796d-4eaa-8dff-529b368b20db"

[[kv_namespaces]]
binding = "kv"
id = "9be10cd058e04c55b526f8c0c116f50c"

#[[r2_buckets]]
#binding = "r2"
#bucket_name = "test-email"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[vars]
orm_log = false
domain = ["example.com"]    # e.g. ["example1.com", "example2.com"]
admin = "admin@example.com"
admin_password = "change-me"
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
